[[headers]]
  for = "/*"  # 모든 경로에 대해 적용
  [headers.values]
    Content-Security-Policy = "default-src 'self' https:; img-src 'self' https: data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
